# Generated by Django 5.2.7 on 2025-10-14 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cars", "0001_initial"),
        ("dealerships", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="dealershipsalehistory",
            name="buyer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="dealershipsalehistory",
            name="car",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="cars.car"
            ),
        ),
        migrations.AddField(
            model_name="dealershipsalehistory",
            name="dealership",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sales_history",
                to="dealerships.dealership",
            ),
        ),
        migrations.AddField(
            model_name="inventory",
            name="car",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="cars.car"
            ),
        ),
        migrations.AddField(
            model_name="inventory",
            name="dealership",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inventory",
                to="dealerships.dealership",
            ),
        ),
        migrations.AddField(
            model_name="preferredmodel",
            name="car",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="cars.car"
            ),
        ),
        migrations.AddField(
            model_name="preferredmodel",
            name="dealership",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="preferred_models",
                to="dealerships.dealership",
            ),
        ),
    ]
