# Generated by Django 5.2.7 on 2025-10-15 21:02

import dealerships.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dealerships", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dealership",
            name="balance",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Balance must be greater than 0",
                max_digits=12,
                validators=[dealerships.validators.validate_positive_value],
            ),
        ),
        migrations.AlterField(
            model_name="dealershipsalehistory",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Balance must be greater than 0",
                max_digits=12,
                validators=[dealerships.validators.validate_positive_value],
            ),
        ),
    ]
