# Generated by Django 5.2.7 on 2025-10-15 22:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dealerships", "0003_alter_dealership_balance_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dealershippromotion",
            name="discount_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Discount rate from 0 to 100",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
