# Generated by Django 5.2.7 on 2025-10-20 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dealerships", "0005_dealershippromotion_created_at_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="dealership",
            unique_together={("name", "country", "city")},
        ),
    ]
