# Generated by Django 5.2.7 on 2025-10-20 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0004_alter_carbrand_country"),
        ("dealerships", "0006_alter_dealership_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="inventory",
            unique_together={("dealership", "car")},
        ),
    ]
