# Generated by Django 5.2.7 on 2025-10-20 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0004_alter_carbrand_country"),
        ("dealerships", "0007_alter_inventory_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="preferredmodel",
            unique_together={("dealership", "car")},
        ),
    ]
