# Generated by Django 5.2.7 on 2025-10-20 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dealerships", "0008_alter_preferredmodel_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dealershippromotion",
            name="end_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="dealershippromotion",
            name="start_date",
            field=models.DateField(),
        ),
    ]
