# Generated by Django 5.2.7 on 2025-10-31 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dealerships", "0009_alter_dealershippromotion_end_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventory",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
