# Generated by Django 5.2.7 on 2025-10-15 21:02

import offers.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offers", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offer",
            name="max_price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Price must be greater than 0",
                max_digits=12,
                validators=[offers.validators.validate_positive_value],
            ),
        ),
    ]
