# Generated by Django 5.2.7 on 2025-10-31 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dealerships", "0010_inventory_price"),
        ("offers", "0003_alter_offer_max_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="offer",
            name="dealership",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="offers",
                to="dealerships.dealership",
            ),
        ),
    ]
