# Generated by Django 5.2.7 on 2025-11-04 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offers", "0004_offer_dealership"),
    ]

    operations = [
        migrations.AddField(
            model_name="offer",
            name="actual_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
    ]
