# Generated by Django 5.2.7 on 2025-10-15 21:02

import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="balance",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Balance must be greater than 0",
                max_digits=12,
                validators=[users.validators.validate_positive_value],
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="total_spent",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Balance must be greater than 0",
                max_digits=12,
                validators=[users.validators.validate_positive_value],
            ),
        ),
    ]
