# Generated by Django 5.2.7 on 2025-10-15 10:55

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("suppliers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplier",
            name="country",
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
