# Generated by Django 5.2.7 on 2025-10-15 21:02

import django.core.validators
import suppliers.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suppliers", "0002_alter_supplier_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplieroffer",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Price must be greater than 0",
                max_digits=12,
                validators=[suppliers.validators.validate_positive_value],
            ),
        ),
        migrations.AlterField(
            model_name="supplierpromotion",
            name="discount_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Discount rate from 0 to 100",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="suppliersalehistory",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Price must be greater than 0",
                max_digits=12,
                validators=[suppliers.validators.validate_positive_value],
            ),
        ),
    ]
