# Generated by Django 5.2.7 on 2025-10-19 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suppliers", "0003_alter_supplieroffer_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplierpromotion",
            name="end_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="supplierpromotion",
            name="start_date",
            field=models.DateField(),
        ),
    ]
