# Generated by Django 5.2.7 on 2025-10-19 17:51

import suppliers.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suppliers", "0004_alter_supplierpromotion_end_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplier",
            name="founded_year",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[suppliers.validators.validate_founded_year],
            ),
        ),
    ]
