# Generated by Django 5.2.7 on 2025-10-22 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suppliers", "0005_alter_supplier_founded_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="suppliersalehistory",
            name="sale_date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
