# Generated by Django 5.2.7 on 2025-10-15 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="car",
            old_name="name",
            new_name="model_name",
        ),
        migrations.AlterUniqueTogether(
            name="car",
            unique_together={("brand", "model_name")},
        ),
    ]
