# Generated by Django 5.2.7 on 2025-10-19 14:54

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0002_rename_name_car_model_name_alter_car_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carbrand",
            name="country",
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
