# Generated by Django 5.2.7 on 2025-10-19 20:20

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0003_alter_carbrand_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carbrand",
            name="country",
            field=django_countries.fields.CountryField(
                blank=True, max_length=2, null=True
            ),
        ),
    ]
